<?php

namespace ProjectBundle\Repository;

/**
 * ChapitreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChapitreRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByProject( $query ) {
        return $this->createQueryBuilder('chapitre')
            ->where('chapitre.project = :project_id')
            ->setParameter('project_id', $query)
            ->getQuery()
            ->execute();
    }
}
