<?php

namespace ProjectBundle\Repository;

/**
 * HerosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HerosRepository extends \Doctrine\ORM\EntityRepository
{
}
