<?php

namespace ProjectBundle\Repository;

/**
 * lexicomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class lexicomRepository extends \Doctrine\ORM\EntityRepository
{
}
